name: chatnova
description: A Final Year Flutter Project
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.5.2
  firebase_auth: ^4.4.2
  firebase_core: ^2.10.0
  firebase_storage: ^11.1.1
  google_fonts: ^4.0.3
  image_picker: ^0.8.7+3
  intl: ^0.18.1
  intl_phone_field: ^3.1.0
  path: ^1.8.2
  provider: ^6.0.5
  shared_preferences: ^2.1.0
  sqflite: ^2.2.7
  flutter_contacts: ^1.1.6
  flutter_paypal: ^0.0.8
  firebase_database: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/launcher_icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
